### ISSUE TITLE
UPD2-repo2: Claim is opened 

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo2-in-SOB#1]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Contract address: [0x13f4fde741bb1a1c68d805a26cf6d96e4c3cc239](https://ropsten.etherscan.io/address/0x13f4fde741bb1a1c68d805a26cf6d96e4c3cc239)
Network: Testnet (Ropsten)
Paid to: annadanchenko
