### ISSUE TITLE
UPD3-repo2: Confirm is active

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo2-in-SOB#2]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Contract address: [0x3296c69061fddb61ca790a7a2e134cdd01ad10c0](https://ropsten.etherscan.io/address/0x3296c69061fddb61ca790a7a2e134cdd01ad10c0)
Network: Testnet (Ropsten)
Status: pending maintainer confirmation
Winner: annadanchenko
